services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/medinow
      - PORT=5000
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
